name: Run JavaScript File
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run JavaScript file
        run: |
          node realTimeAnalyticsJSscript.js
